name: corralnotes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^3.5.0
  the_apple_sign_in: ^1.1.1
  uuid: ^3.0.6
  oktoast: ^3.0.0
  intl: ^0.17.0
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Hellix
      fonts:
        - asset: assets/fonts/Hellix-Regular.ttf
          weight: 300 
        - asset: assets/fonts/Hellix-Bold.ttf
          weight: 600 
        - asset: assets/fonts/Hellix-Thin.ttf
          weight: 300  
  
